name: CI

on:
  push:
    branches:
      - master
      - main

jobs:
  build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DEPLOYMENT_DOCKER_REGISTRY }}
          username: ${{ secrets.DEPLOYMENT_DOCKER_USERNAME }}
          password: ${{ secrets.DEPLOYMENT_DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DEPLOYMENT_DOCKER_REGISTRY }}/poll:v1
          cache-from: type=gha
          cache-to: type=gha,mode=max
